# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-30 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180630_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='testing2',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testing2',
            name='last',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testing2',
            name='message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='testing2',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
